### ISSUE TITLE
Outdated Textures

### ISSUE THREAD

**Issue by Crackers0106** [inteneich/MCT-Plus#2]
There's textures in here from older versions of PA+ that were replaced a long time ago, for example:
Netherite Ingot
Bamboo plants
Bee Nest top texture
Smithing table sides

Possibly more other than those examples, I would look through the pack files and compare their contents to the latest version of the Java edition of the pack to be sure.

**Comment by inteneich** [comment]
Currently working on this issue.
Not only does it seems like there are outdated textures, but I've also found some missing and some of them were not named correctly. Working on the misnamed and missing first, then I will check the outdated textures in a week.

**Comment by inteneich** [comment]
OK, the textures are now more or less updated. Closing the issue.
